import { Feature, FloatingCard } from "@/types";

export const heroFloatingCards: FloatingCard[] = [
  {
    id: "study-sessions",
    title: "Study Sessions",
    description: "Live sessions with peers and subject experts.",
    meta: "Today · 7:00 PM ET",
    icon: "Video",
    avatarCount: 24,
  },
  {
    id: "study-circles",
    title: "Study Circles (Group Study)",
    description: "Collaborate in small groups and make progress together.",
    icon: "Users",
    avatarCount: 18,
  },
  {
    id: "assist",
    title: "Assist",
    description: "AI-powered academic support to help you understand and grow.",
    meta: "Always available",
    icon: "Bot",
  },
  {
    id: "tutoring",
    title: "Tutoring",
    description: "Connect with instructors 1:1 when you need personalized support.",
    icon: "UserCheck",
  },
];

export const featureStrip: Feature[] = [
  {
    id: "global",
    title: "Global & Virtual",
    description: "Join students and educators from 72+ countries.",
    icon: "Globe",
  },
  {
    id: "accessible",
    title: "Accessible Anywhere",
    description: "Learn, teach, and connect from any device, anytime.",
    icon: "Accessible",
  },
  {
    id: "safe",
    title: "Safe & Secure",
    description: "Your privacy and data protection are our priority.",
    icon: "Shield",
  },
  {
    id: "support",
    title: "24/7 Support",
    description: "AI, peers, and educators help when you need it.",
    icon: "Headphones",
  },
  {
    id: "goals",
    title: "Achieve Your Goals",
    description: "Resources, opportunities, and a community that helps you win.",
    icon: "Trophy",
  },
];

export const exploreFeatures: Feature[] = [
  {
    id: "one-channel",
    title: "ONE Channel",
    description: "Your academic home base. A personalized feed of activity, updates, and announcements from your courses, circles, and network.",
    icon: "Home",
    href: "/features/one-channel",
    tag: "Dashboard",
    bullets: [
      "Personalized activity feed",
      "Course & circle announcements",
      "Pinned resources & quick links",
      "Notification center",
    ],
  },
  {
    id: "threads",
    title: "Threads",
    description: "Real-time academic discussions. Ask questions, share insights, and engage with your peers and instructors in organized topic threads.",
    icon: "MessageSquare",
    href: "/features/threads",
    tag: "Discussion",
    bullets: [
      "Topic-based threaded posts",
      "Rich text, images & file sharing",
      "Upvotes, replies & mentions",
      "Pinned & featured threads",
    ],
  },
  {
    id: "study-sessions-feature",
    title: "Study Sessions",
    description: "Schedule and join live virtual sessions for collaborative study, exam prep, and peer learning with video, screen sharing, and whiteboards.",
    icon: "Video",
    href: "/features/study-sessions",
    tag: "Live Learning",
    bullets: [
      "Live video & screen sharing",
      "Interactive whiteboard tools",
      "Session scheduling & RSVP",
      "Recordings & session notes",
    ],
  },
  {
    id: "study-circle",
    title: "Study Circles",
    description: "Form or join small, focused academic groups. Share resources, tackle assignments together, and hold each other accountable.",
    icon: "UsersRound",
    href: "/features/study-circles",
    tag: "Group Study",
    bullets: [
      "Create or join study groups",
      "Shared task lists & goals",
      "Group chat & file sharing",
      "Progress tracking together",
    ],
  },
  {
    id: "assist-feature",
    title: "Assist (AI)",
    description: "Your intelligent academic companion. Get instant explanations, study plans, essay feedback, and answers powered by AI, available 24/7.",
    icon: "Bot",
    href: "/features/assist",
    tag: "AI-Powered",
    bullets: [
      "Instant question & answer",
      "Personalized study plans",
      "Essay & assignment feedback",
      "Concept explanations & quizzes",
    ],
  },
  {
    id: "tutoring-feature",
    title: "Tutoring",
    description: "Connect 1-on-1 with qualified instructors and tutors for personalized academic support. Book sessions, share materials, and track progress.",
    icon: "UserCheck",
    href: "/features/tutoring",
    tag: "1-on-1 Support",
    bullets: [
      "Find & book verified tutors",
      "Live & async tutoring sessions",
      "Session notes & recordings",
      "Rate & review your tutor",
    ],
  },
  {
    id: "library",
    title: "Library",
    description: "A rich, searchable academic resource hub. Browse notes, eBooks, lecture recordings, past papers, and curated study guides.",
    icon: "BookOpen",
    href: "/features/library",
    tag: "Resources",
    bullets: [
      "Notes, eBooks & study guides",
      "Lecture recordings & slides",
      "Past papers & exam resources",
      "Upload & share your own content",
    ],
  },
  {
    id: "community",
    title: "Community",
    description: "Build your academic identity and network. Follow peers, join interest-based communities, celebrate wins, and support each other.",
    icon: "Heart",
    href: "/features/community",
    tag: "Social",
    bullets: [
      "Student & instructor profiles",
      "Interest-based communities",
      "Recognition & milestone badges",
      "Events, clubs & meetups",
    ],
  },
  {
    id: "network",
    title: "Network",
    description: "Discover career opportunities, internships, mentors, and academic partnerships. Grow your professional network while still in school.",
    icon: "Network",
    href: "/features/network",
    tag: "Opportunities",
    bullets: [
      "Internship & job listings",
      "Mentor matching & connections",
      "Academic partnerships & grants",
      "Portfolio & achievement showcase",
    ],
  },
];

